#### Perceptron (Scratch)

In [1]:
import numpy as np

In [2]:
class PerceptronScratch:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    
    def train(self, X, Y, n_iteration=10, alpha=0.1, threshold = 0):
        for i in range(n_iteration):
            print("Iteration", i + 1, "\n")
            print("{:<5}{:<5}{:<10}{:<10}{:<10}{:<5}{:<5}".format("X1", "X2", "TARGET", "PREDICTED", "ERROR", "W1", "W2"))
            for x, y in zip(X, Y):
                result = (self.weights[0] * x[0]) + (self.weights[1] * x[1]) + self.bias
                if result > threshold:
                    result = 1
                else:
                    result = 0
                
                error = y - result
                self.weights += alpha * error * x

                print("{:<5}{:<5}{:<10}{:<10}{:<10}{:<5}{:<5}".format(x[0], x[1], y, result, error, self.weights[0], self.weights[1]))

            y_pred = []

            for x, y in zip(X, Y):
                result = (self.weights[0] * x[0]) + (self.weights[1] * x[1]) + self.bias
                y_pred.append(1 if result > threshold else 0)
            
            comparision = Y == y_pred

            print()

            if comparision.all():
                break


#### AND Gate

In [3]:
model_and = PerceptronScratch(weights=[0.3, -0.2], bias=-0.4)

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])

model_and.train(x, y)

Iteration 1 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    0         0         0         0.3  -0.2 
0    1    0         0         0         0.3  -0.2 
1    0    0         0         0         0.3  -0.2 
1    1    1         0         1         0.4  -0.1 

Iteration 2 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    0         0         0         0.4  -0.1 
0    1    0         0         0         0.4  -0.1 
1    0    0         0         0         0.4  -0.1 
1    1    1         0         1         0.5  0.0  

Iteration 3 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    0         0         0         0.5  0.0  
0    1    0         0         0         0.5  0.0  
1    0    0         1         -1        0.4  0.0  
1    1    1         0         1         0.5  0.1  

Iteration 4 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    0         0         0         0.5  0.1  
0    1    0         0         0         0.5  0.1  
1    0    0         1  

#### OR Gate

In [4]:
model_or = PerceptronScratch(weights=[0.3, -0.2], bias=-0.4)

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 1])

model_or.train(x, y)

Iteration 1 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    0         0         0         0.3  -0.2 
0    1    1         0         1         0.3  -0.1 
1    0    1         0         1         0.4  -0.1 
1    1    1         0         1         0.5  0.0  

Iteration 2 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    0         0         0         0.5  0.0  
0    1    1         0         1         0.5  0.1  
1    0    1         1         0         0.5  0.1  
1    1    1         1         0         0.5  0.1  

Iteration 3 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    0         0         0         0.5  0.1  
0    1    1         0         1         0.5  0.2  
1    0    1         1         0         0.5  0.2  
1    1    1         1         0         0.5  0.2  

Iteration 4 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    0         0         0         0.5  0.2  
0    1    1         0         1         0.5  0.30000000000000004
1    0   

#### NAND Gate

In [5]:
model_nand = PerceptronScratch(weights=[-0.3, 0.2], bias=0.4)

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([1, 1, 1, 0])

model_nand.train(x, y)

Iteration 1 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    1         1         0         -0.3 0.2  
0    1    1         1         0         -0.3 0.2  
1    0    1         1         0         -0.3 0.2  
1    1    0         1         -1        -0.4 0.1  

Iteration 2 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    1         1         0         -0.4 0.1  
0    1    1         1         0         -0.4 0.1  
1    0    1         0         1         -0.300000000000000040.1  
1    1    0         1         -1        -0.4 0.0  

Iteration 3 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    1         1         0         -0.4 0.0  
0    1    1         1         0         -0.4 0.0  
1    0    1         0         1         -0.300000000000000040.0  
1    1    0         1         -1        -0.4 -0.1 

Iteration 4 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    1         1         0         -0.4 -0.1 
0    1    1         1         0         -0.4

#### NOR

In [6]:
model_nor = PerceptronScratch(weights=[-0.3, 0.2], bias=0.4)

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([1, 0, 0, 0])

model_nor.train(x, y)

Iteration 1 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    1         1         0         -0.3 0.2  
0    1    0         1         -1        -0.3 0.1  
1    0    0         1         -1        -0.4 0.1  
1    1    0         1         -1        -0.5 0.0  

Iteration 2 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    1         1         0         -0.5 0.0  
0    1    0         1         -1        -0.5 -0.1 
1    0    0         0         0         -0.5 -0.1 
1    1    0         0         0         -0.5 -0.1 

Iteration 3 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    1         1         0         -0.5 -0.1 
0    1    0         1         -1        -0.5 -0.2 
1    0    0         0         0         -0.5 -0.2 
1    1    0         0         0         -0.5 -0.2 

Iteration 4 

X1   X2   TARGET    PREDICTED ERROR     W1   W2   
0    0    1         1         0         -0.5 -0.2 
0    1    0         1         -1        -0.5 -0.30000000000000004
1    0  

#### Perceptron (Scikit Learn)

In [7]:
from sklearn.linear_model import Perceptron

#### AND

In [8]:
model_and = Perceptron()

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])

model_and.fit(x, y)
model_and.predict(x)

array([0, 0, 0, 1])

#### OR

In [9]:
model_or = Perceptron()

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 1])

model_or.fit(x, y)
model_or.predict(x)

array([0, 1, 1, 1])

#### NAND

In [10]:
model_nand = Perceptron()

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([1, 1, 1, 0])

model_nand.fit(x, y)
model_nand.predict(x)

array([1, 0, 0, 0])

#### NOR

In [11]:
model_nor = Perceptron()

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([1, 0, 0, 0])

model_nor.fit(x, y)
model_nor.predict(x)

array([1, 0, 0, 0])