In [1]:
 import numpy as np

In [14]:
#AND_GATE
x1=np.array([0,0,1,1])
x2=np.array([0,1,0,1])

y=np.array([0,0,0,1]) 
w1=int(input('Enter the weight-1 : ')) 
w2=int(input('Enter the weight-2 : ')) 
fx=x1*w1+x2*w2
print('f(x) : ',fx)

threshold=int(input('Enter the threshold : ')) 
y_out=(fx>=threshold).astype(int) 
print(y_out)
if np.all (y==y_out):

    print('\nThe weights and threshold are correct') 
else:
    print('\nChange the weights and threshold')
    
#112

Enter the weight-1 : 1
Enter the weight-2 : 1
f(x) :  [0 1 1 2]
Enter the threshold : 2
[0 0 0 1]

The weights and threshold are correct


In [9]:
#OR_GATE
x1=np.array([0,0,1,1])
x2=np.array([0,1,0,1])

y=np.array([0,1,1,1]) 
w1=int(input('Enter the weight-1 : ')) 
w2=int(input('Enter the weight-2 : ')) 
fx=x1*w1+x2*w2
print('f(x) : ',fx)

threshold=int(input('Enter the threshold : '))
y_out=(fx>=threshold).astype(int)
print(y_out)
if np.all (y==y_out):

    print('\nThe weights and threshold are correct') 
else:
    print('\nChange the weights and threshold')
    
#111

Enter the weight-1 : 1
Enter the weight-2 : 1
f(x) :  [0 1 1 2]
Enter the threshold : 1
[0 1 1 1]

The weights and threshold are correct


In [10]:
#NAND_GATE
x1=np.array([0,0,1,1])
x2=np.array([0,1,0,1])

y=np.array([1,1,1,0])

w1=int(input('Enter the weight-1 : ')) 
w2=int(input('Enter the weight-2 : ')) 
fx=x1*w1+x2*w2
print(fx)

threshold=int(input('Enter the threshold : ')) 
y_out=(fx>=threshold).astype(int) 
print(y_out)
if np.all (y==y_out):

    print('correct weights and threshold') 
else:
    print('change the weights and threshold')
    
#-1-1-1

Enter the weight-1 : -1
Enter the weight-2 : -1
[ 0 -1 -1 -2]
Enter the threshold : -1
[1 1 1 0]
correct weights and threshold


In [11]:
#NOR_GATE
x1=np.array([0,0,1,1])
x2=np.array([0,1,0,1])

y=np.array([1,0,0,0]) 
w1=int(input('Enter the weight-1 : ')) 
w2=int(input('Enter the weight-2 : ')) 
fx=x1*w1+x2*w2
print(fx)

threshold=int(input('Enter the threshold : '))

y_out=(fx>=threshold).astype(int) 
print(y_out)
if np.all (y==y_out):

    print('correct weights and threshold') 
else:
    print('change the weights and threshold')
    
#-1-10    

Enter the weight-1 : -1
Enter the weight-2 : -1
[ 0 -1 -1 -2]
Enter the threshold : 0
[1 0 0 0]
correct weights and threshold


In [13]:
#NOR_GATE
x=np.array([0,1])
y=np.array([1,0]) 
w=int(input('Enter the weight : ')) 
fx=x*w
print(fx)

threshold=int(input('Enter the threshold : ')) 
y_out=(fx>=threshold).astype(int) 
print(y_out)
if np.all (y==y_out):

    print('correct weights and threshold') 
else:
    print('change the weights and threshold')

#-10

Enter the weight : -1
[ 0 -1]
Enter the threshold : 0
[1 0]
correct weights and threshold
